### ISSUE TITLE
大佬请问下 这里得hash 是sha1吗？

### ISSUE THREAD

**Issue by user1121114685** [yanjunhui/aliyundrive_open#1]
https://github.com/yanjunhui/aliyundrive_open/blob/main/file.go#L23

**Comment by user1121114685** [comment]
https://www.yuque.com/aliyundrive/zpfszx/zqkqp6
没救了 5秒内5次

**Comment by yanjunhui** [comment]
我也没拿到内测权限啊......
我现在是"借用"的别人的应用信息测试的. 
权限比较高, 基本上没发现限制.

**Comment by yanjunhui** [comment]
其实还好. 文件列表是可以一次性缓存的. 反正以后从文件列表也拿不到下载地址了. 只需要缓存文件信息就行了.
实际下载或者加载播放的时候, 再去请求downloadURL或者playInfo 拿地址

**Comment by yanjunhui** [comment]
https://github.com/yanjunhui/aliyundrive_open/blob/main/file.go#L23
不太确定 现在没地方用得到这个信息

**Comment by user1121114685** [comment]
我也没通过a，就离谱。根本就不会联系我们

**Comment by yanjunhui** [comment]
现在估计还是主要邀请那些已经有稳定用户群的产品加入内测吧  等吧
